version: '3.0'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: fib
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8082:80"
    stdin_open: true
    tty: true

  adminer:
    container_name: adminerMysql
    image: adminer
    restart: always
    ports:
      - 8083:8080
    links:
      - db:db
    depends_on:
      - db
    