version: '3.0'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: fib
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
<<<<<<< HEAD
      - "3307:3306"
=======
      - "3306:3306"

>>>>>>> 45b1d4ae8470e5af405d7ca960765ad341342c6a
  web:
    build: .
    # image: virgilioneto/laravel-ready
    container_name: php_web
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/
    ports:
      - "8082:80"
    links:
      - db:db
    depends_on:
      - db

  adminer:
    container_name: adminerMysql
    image: adminer
    restart: always
    ports:
      - 8083:8080
    links:
      - db:db
    depends_on:
      - db
    
