version: '3.0'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: fib
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "8889:3306"
  web:
    image: virgilioneto/laravel-ready
    container_name: php_web
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8082:80"
    stdin_open: true
    tty: true
